/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.snobot.sd.drivetrainCal;

/**
 *
 * @author PJ
 */
public class DrivetrainCalBox extends javax.swing.JPanel
{

    /**
     * Creates new form DrivetrainCalBox
     */
    public DrivetrainCalBox()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Wheel Bias[0]");
        add(jLabel1, new java.awt.GridBagConstraints());

        jTextField1.setText("jTextField1");
        add(jTextField1, new java.awt.GridBagConstraints());

        jLabel2.setText("Wheel Bias[0]");
        add(jLabel2, new java.awt.GridBagConstraints());

        jTextField2.setText("jTextField1");
        add(jTextField2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
